Repository Autodesk/maya-hydra, pull requests merged in 2023-12, with the labels that each got.

#25 Update mayahydra_version.info
  cmake/mayahydra_version.info
Labels: ready-for-merge, build

#26 Selection change functors now take scene index as argument.
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
Labels: ready-for-merge, core

#30 HYDRA-723 : Fix for Maya Lighting mode not working
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.h
Labels: bug, ready-for-merge
