Repository Autodesk/maya-hydra, pull requests merged in 2024-09, with the labels that each got.

#164 Isolate select scene index, with command-based implementation.
  lib/flowViewport/API/perViewportSceneIndicesData/fvpViewportInformationAndSceneIndicesPerViewportDataManager.cpp
  lib/flowViewport/API/perViewportSceneIndicesData/fvpViewportInformationAndSceneIndicesPerViewportDataManager.h
  lib/flowViewport/debugCodes.cpp
  lib/flowViewport/debugCodes.h
  lib/flowViewport/sceneIndex/CMakeLists.txt
  lib/flowViewport/sceneIndex/fvpIsolateSelectSceneIndex.cpp
  lib/flowViewport/sceneIndex/fvpIsolateSelectSceneIndex.h
  lib/flowViewport/selection/fvpPathMapperRegistry.cpp
  lib/flowViewport/selection/fvpPathMapperRegistry.h
  lib/flowViewport/selection/fvpSelection.cpp
  lib/flowViewport/selection/fvpSelection.h
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.h
  lib/mayaHydra/hydraExtensions/sceneIndex/registration.cpp
  lib/mayaHydra/mayaPlugin/pluginDebugCodes.cpp
  lib/mayaHydra/mayaPlugin/pluginDebugCodes.h
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/testIsolateSelect.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testIsolateSelect.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPathMapperRegistry.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUtils.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUtils.h
Labels: ready-for-merge, fvp-toolkit, sceneindex

#166 Update maya-hydra-preflight-launcher.yml
  .github/workflows/maya-hydra-preflight-launcher.yml
Labels: build

#161 HYDRA-686 : Fix manual lifetime management of MayaHydraSceneIndex's adapters
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.h
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
Labels: ready-for-merge

#165 HYDRA-1132 : Native instance prototypes picking/selection
  lib/flowViewport/fvpUtils.cpp
  lib/flowViewport/fvpUtils.h
  lib/flowViewport/sceneIndex/fvpPathInterface.h
  lib/flowViewport/selection/fvpSelection.cpp
  lib/mayaHydra/hydraExtensions/pick/mhUsdPickHandler.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/registration.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/testDataProducerExample.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUsdNativeInstancePicking.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUsdPickKind.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUsdPicking.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUsdPointInstancePicking.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUsdPointInstancePicking.py
  test/testSamples/testUsdNativeInstances/instancedCubeHierarchies.usda
Labels: ready-for-merge

#169 Lanierd/hydra 1054
  lib/flowViewport/sceneIndex/fvpDefaultMaterialSceneIndex.cpp
  lib/mayaHydra/hydraExtensions/mixedUtils.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/registration.cpp
  test/lib/mayaUsd/render/mayaToHydra/MayaDefaultMaterialTest/defaultMaterialUsdPrims.png
  test/lib/mayaUsd/render/mayaToHydra/testMayaDefaultMaterial.py
  test/testSamples/testDefaultMaterial/testMayaDefaultMaterial_Usd_proceduralShapes.ma
Labels: ready-for-merge

#177 Connect isolate select to Maya UI, and empty isolate selection correctness.
  cmake/modules/FindMaya.cmake
  lib/flowViewport/API/perViewportSceneIndicesData/fvpViewportInformationAndSceneIndicesPerViewportDataManager.cpp
  lib/flowViewport/API/perViewportSceneIndicesData/fvpViewportInformationAndSceneIndicesPerViewportDataManager.h
  lib/flowViewport/sceneIndex/fvpIsolateSelectSceneIndex.cpp
  lib/flowViewport/sceneIndex/fvpIsolateSelectSceneIndex.h
  lib/flowViewport/selection/fvpPathMapperRegistry.cpp
  lib/flowViewport/selection/fvpPathMapperRegistry.h
  lib/flowViewport/selection/fvpSelection.cpp
  lib/flowViewport/selection/fvpSelection.h
  lib/mayaHydra/mayaPlugin/CMakeLists.txt
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
  lib/mayaHydra/mayaPlugin/renderOverride.h
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/IsolateSelectTest/singleViewportIsolateSelectCylinder1.png
  test/lib/mayaUsd/render/mayaToHydra/cpp/testIsolateSelect.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testIsolateSelect.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUtils.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUtils.h
Labels: ready-for-merge

#179 Fix Linux warning as error build break.
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
Labels: ready-for-merge
