Repository Autodesk/maya-hydra, pull requests merged in 2024-03, with the labels that each got.

#91 HYDRA-762 - Investigate why the tumbling performance of USD scene is slower than corresponding Maya Scene under Hydra Storm
  lib/flowViewport/sceneIndex/fvpWireframeSelectionHighlightSceneIndex.cpp
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/testSceneCorrectness.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testSceneCorrectness.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testWireframeSelectionHighlightSceneIndex.cpp
Labels: bug, ready-for-merge, test

#96 try to fix rpath issue
  plugin/mayaHydraSceneBrowser/CMakeLists.txt
Labels: ready-for-merge

#98 HYDRA-746 : Fix the crash when mayaHydra is not loaded and rename classes
  lib/mayaHydra/flowViewportAPIExamples/CMakeLists.txt
  lib/mayaHydra/flowViewportAPIExamples/flowViewportAPILocator/CMakeLists.txt
  lib/mayaHydra/flowViewportAPIExamples/flowViewportAPILocator/mhFlowViewportAPILocator.cpp
  test/lib/mayaUsd/render/mayaToHydra/testFlowViewportAPI.py
Labels: ready-for-merge, fvp-toolkit

#97 HYDRA-689 : Add a flow viewport toolkit API .md file
  README.md
  doc/flowViewportToolkit.md
  doc/images/fvpMergingSceneIndex.png
  lib/flowViewport/API/fvpDataProducerSceneIndexInterface.h
Labels: documentation, fvp-toolkit

#94 HYDRA-843 : Add picking test + Link C++ tests with Qt for UI/viewport interaction
  cmake/compiler_config.cmake
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPicking.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPicking.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUtils.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUtils.h
Labels: ready-for-merge, test

#101 HYDRA-926 : Remove Maya Hydra Scene Producer wrapper
  doc/codingGuidelines.md
  doc/mayaHydraDetails.md
  lib/mayaHydra/hydraExtensions/CMakeLists.txt
  lib/mayaHydra/hydraExtensions/adapters/adapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/adapter.h
  lib/mayaHydra/hydraExtensions/adapters/adapterRegistry.h
  lib/mayaHydra/hydraExtensions/adapters/aiSkydomeLightAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/areaLightAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/cameraAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/cameraAdapter.h
  lib/mayaHydra/hydraExtensions/adapters/dagAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/dagAdapter.h
  lib/mayaHydra/hydraExtensions/adapters/directionalLightAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/lightAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/lightAdapter.h
  lib/mayaHydra/hydraExtensions/adapters/materialAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/materialAdapter.h
  lib/mayaHydra/hydraExtensions/adapters/meshAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/nurbsCurveAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/pointLightAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/renderItemAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/renderItemAdapter.h
  lib/mayaHydra/hydraExtensions/adapters/shapeAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/shapeAdapter.h
  lib/mayaHydra/hydraExtensions/adapters/spotLightAdapter.cpp
  lib/mayaHydra/hydraExtensions/mayaHydraSceneProducer.cpp
  lib/mayaHydra/hydraExtensions/mayaHydraSceneProducer.h
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.h
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
  lib/mayaHydra/mayaPlugin/renderOverride.h
Labels: ready-for-merge, core, sceneindex

#104 Fix code coverage build issue
  lib/mayaHydra/flowViewportAPIExamples/footPrintNode/CMakeLists.txt
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
  lib/mayaHydra/mayaPlugin/renderOverride.h
Labels: bug, ready-for-merge

#103 HYDRA-931 : implement basics of bounding box display style
  lib/flowViewport/API/perViewportSceneIndicesData/fvpFilteringSceneIndicesChainManager.cpp
  lib/flowViewport/API/samples/fvpDataProducerSceneIndexExample.cpp
  lib/flowViewport/sceneIndex/CMakeLists.txt
  lib/flowViewport/sceneIndex/fvpBBoxSceneIndex.cpp
  lib/flowViewport/sceneIndex/fvpBBoxSceneIndex.h
  lib/mayaHydra/flowViewportAPIExamples/footPrintNode/mhFootPrintNode.cpp
  lib/mayaHydra/hydraExtensions/adapters/adapter.h
  lib/mayaHydra/hydraExtensions/adapters/renderItemAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/renderItemAdapter.h
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraDataSource.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraDataSource.h
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
  lib/mayaHydra/mayaPlugin/renderOverride.h
  test/lib/mayaUsd/render/mayaToHydra/MayaDisplayModesTest/BBox_DisplayModeOn.png
  test/lib/mayaUsd/render/mayaToHydra/MayaDisplayModesTest/BBox_sceneLoaded.png
  test/lib/mayaUsd/render/mayaToHydra/MayaShadingModesTest/boundingBox.png
  test/lib/mayaUsd/render/mayaToHydra/testMayaDisplayModes.py
  test/testSamples/testMayaDisplayModes/PoolBallFlat_animated.usdz
  test/testSamples/testMayaDisplayModes/testMayaBoundingBoxDisplayMode.ma
Labels: ready-for-merge

#105 Point instance picking support (no selection highlighting)
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.cpp
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
  lib/mayaHydra/mayaPlugin/renderOverride.h
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPicking.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPointInstancePicking.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPointInstancePicking.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUtils.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUtils.h
  test/testSamples/testPointInstances/CubeModel.usda
  test/testSamples/testPointInstances/PyramidModel.usda
  test/testSamples/testPointInstances/nestedPointInstancers.usda
Labels: ready-for-merge

#109 Avoid Maya Hydra registration for mayaUsdPlugin if not loaded.
  lib/mayaHydra/hydraExtensions/sceneIndex/registration.cpp
Labels: ready-for-merge

#107 Native instance picking.
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUsdNativeInstancePicking.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUsdNativeInstancePicking.py
  test/testSamples/testUsdNativeInstances/cubesHierarchy.usda
  test/testSamples/testUsdNativeInstances/instancedCubeHierarchies.usda
Labels: ready-for-merge

#106 HYDRA-927 - Expose complexity settings in globalRenderSettings
  lib/flowViewport/sceneIndex/CMakeLists.txt
  lib/flowViewport/sceneIndex/fvpDisplayStyleOverrideSceneIndex.cpp
  lib/flowViewport/sceneIndex/fvpDisplayStyleOverrideSceneIndex.h
  lib/mayaHydra/hydraExtensions/mayaHydraParams.h
  lib/mayaHydra/mayaPlugin/renderGlobals.cpp
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
  lib/mayaHydra/mayaPlugin/renderOverride.h
  lib/mayaHydra/mayaPlugin/tokens.h
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/RefinementTest/usd_cube_refined_0.png
  test/lib/mayaUsd/render/mayaToHydra/RefinementTest/usd_cube_refined_2.png
  test/lib/mayaUsd/render/mayaToHydra/RefinementTest/usd_cube_refined_4.png
  test/lib/mayaUsd/render/mayaToHydra/testRefinement.py
Labels: ready-for-merge

#108 HYDRA-861 & HYDRA-932 : Fix MtoA & LookdevX loading in tests + Related test improvements
  cmake/test.cmake
  test/lib/mayaUsd/render/mayaToHydra/README.md
  test/lib/mayaUsd/render/mayaToHydra/cpp/testMayaUsdUfeItems.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPathInterface.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPicking.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPointInstancePicking.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPrimInstancing.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testSceneCorrectness.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUsdNativeInstancePicking.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUsdStageLayerMuting.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testWireframeSelectionHighlightSceneIndex.py
  test/lib/mayaUsd/render/mayaToHydra/testArnoldLights.py
  test/lib/mayaUsd/render/mayaToHydra/testCurveTools.py
  test/lib/mayaUsd/render/mayaToHydra/testFlowViewportAPI.py
  test/lib/mayaUsd/render/mayaToHydra/testFootPrintNode.py
  test/lib/mayaUsd/render/mayaToHydra/testImageDiffing.py
  test/lib/mayaUsd/render/mayaToHydra/testLookThrough.py
  test/lib/mayaUsd/render/mayaToHydra/testMaterialXOnNative.py
  test/lib/mayaUsd/render/mayaToHydra/testMayaDisplayLayers.py
  test/lib/mayaUsd/render/mayaToHydra/testMayaDisplayModes.py
  test/lib/mayaUsd/render/mayaToHydra/testMayaIsolateSelect.py
  test/lib/mayaUsd/render/mayaToHydra/testMayaLights.py
  test/lib/mayaUsd/render/mayaToHydra/testMayaShadingModes.py
  test/lib/mayaUsd/render/mayaToHydra/testMayaUsdAPIUsage.py
  test/lib/mayaUsd/render/mayaToHydra/testMtohBasicRender.py
  test/lib/mayaUsd/render/mayaToHydra/testMtohDagChanges.py
  test/lib/mayaUsd/render/mayaToHydra/testNewSceneWithStage.py
  test/lib/mayaUsd/render/mayaToHydra/testNurbsPrimitives.py
  test/lib/mayaUsd/render/mayaToHydra/testObjectTemplate.py
  test/lib/mayaUsd/render/mayaToHydra/testPolygonPrimitives.py
  test/lib/mayaUsd/render/mayaToHydra/testRefinement.py
  test/lib/mayaUsd/render/mayaToHydra/testSceneBrowser.py
  test/lib/mayaUsd/render/mayaToHydra/testStageAddPrim.py
  test/lib/mayaUsd/render/mayaToHydra/testStagePayloadsReferences.py
  test/lib/mayaUsd/render/mayaToHydra/testStageVariants.py
  test/lib/mayaUsd/render/mayaToHydra/testStandardSurface.py
  test/lib/mayaUsd/render/mayaToHydra/testTransforms.py
  test/lib/mayaUsd/render/mayaToHydra/testUSDLights.py
  test/lib/mayaUsd/render/mayaToHydra/testVisibility.py
  test/testSamples/testArnoldLights/UsdStageWithSphereMatXStdSurf.usd
  test/testSamples/testArnoldLights/UsdStageWithSphereMatXStdSurf.usda
  test/testSamples/testArnoldLights/testArnoldLights.ma
  test/testSamples/testMayaDisplayModes/testMayaDisplayModes.ma
  test/testSamples/testMayaLights/UsdStageWithSphereMatXStdSurf.usd
  test/testSamples/testMayaLights/UsdStageWithSphereMatXStdSurf.usda
  test/testSamples/testMayaLights/testMayaLights.ma
  test/testSamples/testMayaUsdAPIUsage/UsdStageWithSphereMatXStdSurf.ma
  test/testSamples/testMayaUsdAPIUsage/UsdStageWithSphereMatXStdSurf.usd
  test/testSamples/testMayaUsdAPIUsage/UsdStageWithSphereMatXStdSurf.usda
  test/testSamples/testStagePayloadsReferences/FlowerPot.ma
  test/testSamples/testStagePayloadsReferences/References.ma
  test/testSamples/testStageVariants/testStageVariants.ma
  test/testSamples/testUSDLights/UsdStageWithSphereMatXStdSurf.usd
  test/testSamples/testUSDLights/UsdStageWithSphereMatXStdSurf.usda
  test/testSamples/testUSDLights/testUSDLights.ma
  test/testUtils/mtohUtils.py
Labels: ready-for-merge, test

#110 HYDRA-837 : Fix color management handling in tests
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/CurveToolsTest/curveControlVertices_basic.png
  test/lib/mayaUsd/render/mayaToHydra/CurveToolsTest/curveControlVertices_bezier.png
  test/lib/mayaUsd/render/mayaToHydra/CurveToolsTest/curveControlVertices_customKnots.png
  test/lib/mayaUsd/render/mayaToHydra/CurveToolsTest/curveControlVertices_degree1.png
  test/lib/mayaUsd/render/mayaToHydra/CurveToolsTest/curveControlVertices_degree2.png
  test/lib/mayaUsd/render/mayaToHydra/CurveToolsTest/curveControlVertices_degree5.png
  test/lib/mayaUsd/render/mayaToHydra/CurveToolsTest/curveEditPoints_basic.png
  test/lib/mayaUsd/render/mayaToHydra/CurveToolsTest/curveEditPoints_bezier.png
  test/lib/mayaUsd/render/mayaToHydra/CurveToolsTest/curveEditPoints_degree1.png
  test/lib/mayaUsd/render/mayaToHydra/CurveToolsTest/curveEditPoints_degree2.png
  test/lib/mayaUsd/render/mayaToHydra/CurveToolsTest/curveEditPoints_degree5.png
  test/lib/mayaUsd/render/mayaToHydra/MayaDisplayLayersTest/coneLayerCustomWireframe.png
  test/lib/mayaUsd/render/mayaToHydra/MayaDisplayLayersTest/layerTemplate.png
  test/lib/mayaUsd/render/mayaToHydra/MayaDisplayLayersTest/layerTemplateSelected.png
  test/lib/mayaUsd/render/mayaToHydra/PolygonPrimitivesTest/cylinder_roundCapHeightCompensation.png
  test/lib/mayaUsd/render/mayaToHydra/PolygonPrimitivesTest/helix_clockwise.png
  test/lib/mayaUsd/render/mayaToHydra/PolygonPrimitivesTest/pipe_roundCapHeightCompensation.png
  test/lib/mayaUsd/render/mayaToHydra/PolygonPrimitivesTest/soccerball_modified.png
  test/lib/mayaUsd/render/mayaToHydra/README.md
  test/lib/mayaUsd/render/mayaToHydra/testArnoldLights.py
  test/lib/mayaUsd/render/mayaToHydra/testCurveTools.py
  test/lib/mayaUsd/render/mayaToHydra/testFootPrintNode.py
  test/lib/mayaUsd/render/mayaToHydra/testLookThrough.py
  test/lib/mayaUsd/render/mayaToHydra/testMayaDisplayLayers.py
  test/lib/mayaUsd/render/mayaToHydra/testMayaDisplayModes.py
  test/lib/mayaUsd/render/mayaToHydra/testMayaIsolateSelect.py
  test/lib/mayaUsd/render/mayaToHydra/testMayaLights.py
  test/lib/mayaUsd/render/mayaToHydra/testMayaShadingModes.py
  test/lib/mayaUsd/render/mayaToHydra/testMayaUsdAPIUsage.py
  test/lib/mayaUsd/render/mayaToHydra/testObjectTemplate.py
  test/lib/mayaUsd/render/mayaToHydra/testPolygonPrimitives.py
  test/lib/mayaUsd/render/mayaToHydra/testUSDLights.py
  test/testUtils/imageUtils.py
  test/testUtils/mayaUtils.py
  test/testUtils/mtohUtils.py
Labels: ready-for-merge, test

#111 HYDRA-538 - Create unit test to verify UVs/UDIMs are rendered accordingly with Maya data
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/UVandUDIMTest/quads_with_UDIMs.png
  test/lib/mayaUsd/render/mayaToHydra/UVandUDIMTest/quads_with_UVs.png
  test/lib/mayaUsd/render/mayaToHydra/testUVandUDIM.py
  test/testSamples/testUVandUDIM/UdimTest_1001_color.png
  test/testSamples/testUVandUDIM/UdimTest_1002_color.png
  test/testSamples/testUVandUDIM/UdimTest_1003_color.png
  test/testSamples/testUVandUDIM/blue.png
  test/testSamples/testUVandUDIM/green.png
  test/testSamples/testUVandUDIM/red.png
  test/testSamples/testUVandUDIM/testUDIMs.ma
  test/testSamples/testUVandUDIM/testUVs.ma
Labels: ready-for-merge, test
