Repository Autodesk/maya-hydra, pull requests merged in 2024-07, with the labels that each got.

#141 HYDRA-712 : Handle hierarchical transform & visibility changes for plugin nodes
  lib/flowViewport/API/interfacesImp/fvpFilteringSceneIndexInterfaceImp.cpp
  lib/flowViewport/API/interfacesImp/fvpFilteringSceneIndexInterfaceImp.h
  lib/flowViewport/API/perViewportSceneIndicesData/fvpDataProducerSceneIndexDataBase.cpp
  lib/flowViewport/API/perViewportSceneIndicesData/fvpDataProducerSceneIndexDataBase.h
  lib/flowViewport/API/perViewportSceneIndicesData/fvpFilteringSceneIndexDataBase.cpp
  lib/flowViewport/API/perViewportSceneIndicesData/fvpFilteringSceneIndexDataBase.h
  lib/flowViewport/API/perViewportSceneIndicesData/fvpFilteringSceneIndicesChainManager.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraMayaDataProducerSceneIndexData.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraMayaDataProducerSceneIndexData.h
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraMayaFilteringSceneIndexData.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraMayaFilteringSceneIndexData.h
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/authoring_locator_parentTransformChanged.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/authoring_locator_shapeTransformChanged.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/authoring_locator_visibility_off.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/authoring_locator_visibility_on.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/locator_playback_hidden.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/locator_playback_initial.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/locator_playback_translated.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStageAnimatedPrim_t0.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStageAnimatedPrim_t1.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStageAnimatedPrim_t10.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStageAnimatedPrim_t12.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStageAnimatedPrim_t15.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStageAnimatedPrim_t3.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStageAnimatedPrim_t5.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStageAnimatedPrim_t7.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStage_parentTransformChanged.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStage_playback_hidden.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStage_playback_initial.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStage_playback_translated.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStage_shapeTransformChanged.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStage_visibility_off.png
  test/lib/mayaUsd/render/mayaToHydra/FlowPluginsHierarchicalPropertiesTest/usdStage_visibility_on.png
  test/lib/mayaUsd/render/mayaToHydra/FlowViewportAPITest/hierarchicalProperties_locator_visibility_off.png
  test/lib/mayaUsd/render/mayaToHydra/FlowViewportAPITest/hierarchicalProperties_locator_visibility_on.png
  test/lib/mayaUsd/render/mayaToHydra/FlowViewportAPITest/hierarchicalProperties_usdStage_parentTransformChanged.png
  test/lib/mayaUsd/render/mayaToHydra/FlowViewportAPITest/hierarchicalProperties_usdStage_shapeTransformChanged.png
  test/lib/mayaUsd/render/mayaToHydra/FlowViewportAPITest/hierarchicalProperties_usdStage_visibility_off.png
  test/lib/mayaUsd/render/mayaToHydra/FlowViewportAPITest/hierarchicalProperties_usdStage_visibility_on.png
  test/lib/mayaUsd/render/mayaToHydra/cpp/testFlowViewportAPIAddPrims.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testFlowViewportAPIFilterPrims.cpp
  test/lib/mayaUsd/render/mayaToHydra/testFlowPluginsHierarchicalProperties.py
  test/testSamples/testFlowPluginsHierarchicalProperties/usd_animated_prim.usda
  test/testUtils/imageUtils.py
  test/testUtils/mtohUtils.py
Labels: ready-for-merge

#145 HYDRA-970 : Test single picking
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/testSinglePicking.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testSinglePicking.py
  test/testSamples/testSinglePicking/testSinglePicking.ma
  test/testSamples/testSinglePicking/testSinglePicking.usda
Labels: ready-for-merge, test

#144 HYDRA-1061 : Fix texture mode toggle on USD data
  lib/flowViewport/sceneIndex/fvpPruneTexturesSceneIndex.cpp
  test/lib/mayaUsd/render/mayaToHydra/UsdTextureToggleTest/usd_texture_off.png
  test/lib/mayaUsd/render/mayaToHydra/UsdTextureToggleTest/usd_texture_on.png
  test/lib/mayaUsd/render/mayaToHydra/testUsdTextureToggle.py
  test/testSamples/testUsdTextureToggle/usdStageWithTexture.usd
Labels: ready-for-merge

#147 HYDRA-1103 : Update face selection shader to behave as an unlit shader
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.cpp
  test/lib/mayaUsd/render/mayaToHydra/MayaComponentsPickingTest/facesSelStorm.png
  test/lib/mayaUsd/render/mayaToHydra/MayaComponentsPickingTest/facesSelVP2.png
  test/lib/mayaUsd/render/mayaToHydra/MayaComponentsPickingTest/selectionWithLights.png
  test/lib/mayaUsd/render/mayaToHydra/MayaComponentsPickingTest/smoothwireframe.png
  test/lib/mayaUsd/render/mayaToHydra/testMayaComponentsPicking.py
Labels: bug, ready-for-merge

#148 HYDRA-1057 : GeomSubsets wireframe highlighting
  lib/flowViewport/sceneIndex/fvpWireframeSelectionHighlightSceneIndex.cpp
  lib/flowViewport/sceneIndex/fvpWireframeSelectionHighlightSceneIndex.h
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
  lib/mayaHydra/mayaPlugin/renderOverride.h
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/DataProducerSelHighlightTest/Storm_AllSelected.png
  test/lib/mayaUsd/render/mayaToHydra/DataProducerSelHighlightTest/Storm_S1And2AndTAndPSelected.png
  test/lib/mayaUsd/render/mayaToHydra/DataProducerSelHighlightTest/Storm_S1And2AndTSelected.png
  test/lib/mayaUsd/render/mayaToHydra/DataProducerSelHighlightTest/Storm_S1And2Selected.png
  test/lib/mayaUsd/render/mayaToHydra/DataProducerSelHighlightTest/Storm_S1Selected.png
  test/lib/mayaUsd/render/mayaToHydra/StageVariantsTest/oneCube.png
  test/lib/mayaUsd/render/mayaToHydra/StageVariantsTest/oneCubeInstanceable.png
  test/lib/mayaUsd/render/mayaToHydra/StageVariantsTest/threeCubes.png
  test/lib/mayaUsd/render/mayaToHydra/StageVariantsTest/threeCubesWithDisplacement.png
  test/lib/mayaUsd/render/mayaToHydra/StageVariantsTest/twoCubes.png
  test/lib/mayaUsd/render/mayaToHydra/cpp/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/GeomSubsetsWireframeHighlightTest/CubeUpperHalf_MeshHighlight_0_topology.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/GeomSubsetsWireframeHighlightTest/SphereUpperHalf_MeshHighlight_0_topology.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/GeomSubsetsWireframeHighlightTest/SphereUpperHalf_MeshHighlight_1_topology.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/testGeomSubsetsPicking.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testGeomSubsetsWireframeHighlight.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testGeomSubsetsWireframeHighlight.py
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPointInstancingWireframeHighlight.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUtils.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testUtils.h
  test/lib/mayaUsd/render/mayaToHydra/cpp/testWireframeSelectionHighlightSceneIndex.cpp
  test/testSamples/testGeomSubsetsWireframeHighlight/GeomSubsetsWireframeHighlightTestScene.usda
  test/testSamples/testGeomSubsetsWireframeHighlight/UpperHalfGeomSubsetCube.usda
  test/testSamples/testGeomSubsetsWireframeHighlight/UpperHalfGeomSubsetSphere.usda
Labels: ready-for-merge

#152 created security.md file
  SECURITY.md
Labels: documentation

#133 Tremblp merge 0.6.2 to dev
  doc/CHANGELOG.md
Labels: documentation, build
