Repository Autodesk/maya-hydra, pull requests merged in 2024-01, with the labels that each got.

#37 HYDRA-776 : Update build doc & script
  CMakeLists.txt
  cmake/jinja.cmake
  doc/build.md
Labels: documentation, ready-for-merge

#39 HYDRA-765 - fix the double transform issue on instanced prims
  lib/flowViewport/API/samples/fvpDataProducerSceneIndexExample.cpp
  lib/flowViewport/API/samples/fvpDataProducerSceneIndexExample.h
  lib/mayaHydra/flowViewportAPIExamples/flowViewportAPIMayaLocator/flowViewportAPIMayaLocator.cpp
Labels: ready-for-merge

#40 HYDRA-793 : Remove the usage of the "fit" on a node in a directional …
  test/lib/mayaUsd/render/mayaToHydra/DirectionalLightsTest/defaultLight.png
  test/lib/mayaUsd/render/mayaToHydra/DirectionalLightsTest/defaultLightFit.png
  test/lib/mayaUsd/render/mayaToHydra/DirectionalLightsTest/directionalLight.png
  test/lib/mayaUsd/render/mayaToHydra/DirectionalLightsTest/directionalLightFit.png
  test/lib/mayaUsd/render/mayaToHydra/testDirectionalLights.py
  test/testSamples/testDirectionalLights/UsdStageWithSphereMatXStdSurf.ma
Labels: ready-for-merge, test

#34 HYDRA-700 : Avoid Boost autolinking libraries
  cmake/compiler_config.cmake
  lib/adskHydraSceneBrowser/lib/CMakeLists.txt
  lib/adskHydraSceneBrowser/test/CMakeLists.txt
  lib/flowViewport/CMakeLists.txt
  lib/mayaHydra/hydraExtensions/CMakeLists.txt
  lib/mayaHydra/ufeExtensions/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/CMakeLists.txt
Labels: ready-for-merge, build

#33 HYDRA-764 : Add prim instancing unit test
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPrimInstancing.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPrimInstancing.py
  test/testSamples/testPrimInstancing/cube.usda
  test/testSamples/testPrimInstancing/instanceableCube.usda
  test/testUtils/usdUtils.py
Labels: ready-for-merge, test

#41 HYDRA-786 - make sure skydome light is not turned off unexpectedly
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.cpp
Labels: ready-for-merge

#44 Fix Broken Link
  doc/CHANGELOG.md
Labels: ready-for-merge

#48 Update mayahydra_version.info to 0.7.0
  cmake/mayahydra_version.info
Labels: ready-for-merge, build
