Repository Autodesk/maya-hydra, pull requests merged in 2025-02, with the labels that each got.

#243 Tremblp/hydra 1413/isolate select keep lighting
  lib/flowViewport/sceneIndex/fvpIsolateSelectSceneIndex.cpp
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/IsolateSelectWithUsdLightingTest/isolateSelectWithUsdLighting.png
  test/lib/mayaUsd/render/mayaToHydra/testIsolateSelectWithUsdLighting.py
  test/testSamples/testIsolateSelectWithUsdLighting/mayaPlusUSDMeshesWithUSDLighting.ma
Labels: ready-for-merge

#245 Lanierd/hydra 685
  lib/flowViewport/API/perViewportSceneIndicesData/fvpFilteringSceneIndicesChainManager.cpp
  lib/flowViewport/API/perViewportSceneIndicesData/fvpViewportInformationAndSceneIndicesPerViewportDataManager.cpp
  lib/flowViewport/sceneIndex/fvpRenderIndexProxy.cpp
  lib/flowViewport/sceneIndex/fvpRenderIndexProxy.h
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.h
  lib/mayaHydra/mayaPlugin/plugin.cpp
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
  lib/mayaHydra/mayaPlugin/renderOverride.h
Labels: ready-for-merge

#247 Replace DataProducersNodeHashCodeToSdfPathRegistry with path mapping.
  lib/flowViewport/selection/fvpPathMapper.h
  lib/flowViewport/selection/fvpPathMapperRegistry.cpp
  lib/flowViewport/selection/fvpPathMapperRegistry.h
  lib/flowViewport/selection/fvpPrefixPathMapper.cpp
  lib/flowViewport/selection/fvpPrefixPathMapper.h
  lib/mayaHydra/flowViewportAPIExamples/flowViewportAPILocator/mhFlowViewportAPILocator.cpp
  lib/mayaHydra/flowViewportAPIExamples/footPrintNode/mhFootPrintNode.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/mhMayaUsdProxyShapeSceneIndex.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testPathMapperRegistry.cpp
Labels: ready-for-merge

#250 HYDRA-1368 - Apply default material on geomSubset
  lib/flowViewport/sceneIndex/fvpDefaultMaterialSceneIndex.cpp
  test/lib/mayaUsd/render/mayaToHydra/MayaDefaultMaterialTest/defaultMaterialGeomSubsetUsdPrims.png
  test/lib/mayaUsd/render/mayaToHydra/testMayaDefaultMaterial.py
  test/testSamples/testDefaultMaterial/cube_geomsubset_material.usda
  test/testSamples/testDefaultMaterial/testMayaDefaultMaterial_Native_Usd_dataProducer.ma
  test/testSamples/testDefaultMaterial/testMayaDefaultMaterial_Usd_geomSubset.ma
Labels: ready-for-merge

#252 Add notes about scene index and performance and another about impleme…
  doc/flowViewportToolkit.md
Labels: documentation, ready-for-merge

#249 HYDRA-1175 : Use LightsManagement scene index instead of removing the…
  CMakeLists.txt
  lib/flowViewport/API/fvpFilteringSceneIndexClient.h
  lib/flowViewport/API/samples/fvpFilteringSceneIndexClientExample.h
  lib/flowViewport/sceneIndex/fvpLightsManagementSceneIndex.cpp
  lib/flowViewport/sceneIndex/fvpLightsManagementSceneIndex.h
  lib/mayaHydra/hydraExtensions/adapters/lightAdapter.cpp
  lib/mayaHydra/hydraExtensions/adapters/lightAdapter.h
  lib/mayaHydra/hydraExtensions/mayaUtils.cpp
  lib/mayaHydra/hydraExtensions/mayaUtils.h
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.cpp
  lib/mayaHydra/hydraExtensions/sceneIndex/mayaHydraSceneIndex.h
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
  lib/mayaHydra/ufeExtensions/Global.cpp
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/MayaLightingModesTest/allLights.png
  test/lib/mayaUsd/render/mayaToHydra/MayaLightingModesTest/allLightsSelected.png
  test/lib/mayaUsd/render/mayaToHydra/MayaLightingModesTest/areaLightSelected.png
  test/lib/mayaUsd/render/mayaToHydra/MayaLightingModesTest/defaultLighting.png
  test/lib/mayaUsd/render/mayaToHydra/MayaLightingModesTest/dirLightSelected.png
  test/lib/mayaUsd/render/mayaToHydra/MayaLightingModesTest/domeLightSelected.png
  test/lib/mayaUsd/render/mayaToHydra/MayaLightingModesTest/noLighting.png
  test/lib/mayaUsd/render/mayaToHydra/MayaLightingModesTest/pointLightSelected.png
  test/lib/mayaUsd/render/mayaToHydra/MayaLightingModesTest/selLights_None.png
  test/lib/mayaUsd/render/mayaToHydra/MayaLightingModesTest/someLightsSelected.png
  test/lib/mayaUsd/render/mayaToHydra/MayaLightingModesTest/sphereLightSelected.png
  test/lib/mayaUsd/render/mayaToHydra/MayaLightingModesTest/spotLightSelected.png
  test/lib/mayaUsd/render/mayaToHydra/testMayaLightingModes.py
  test/lib/mayaUsd/render/mayaToHydra/testMayaLights.py
  test/testSamples/testMayaLightingModes/AllKindOfLights.usd
  test/testSamples/testMayaLightingModes/AllKindsOfLights.ma
  test/testSamples/testMayaLightingModes/rubiksCube.usda
  test/testSamples/testMayaLightingModes/rubiksCube_A/bind/rubiksCube_A_bind.usda
  test/testSamples/testMayaLightingModes/rubiksCube_A/geo/rubiksCube_A_proxy.usd
  test/testSamples/testMayaLightingModes/rubiksCube_A/geo/rubiksCube_A_render.usd
  test/testSamples/testMayaLightingModes/rubiksCube_A/mtl/rubiksCube_A_mtl.usda
  test/testSamples/testMayaLightingModes/rubiksCube_A/rubiksCube_A.usda
Labels: ready-for-merge

#255 Image file writing, with test.
  lib/flowViewport/CMakeLists.txt
  lib/flowViewport/imageWriter/CMakeLists.txt
  lib/flowViewport/imageWriter/fvpImageBufferWriter.cpp
  lib/flowViewport/imageWriter/fvpImageBufferWriter.h
  lib/flowViewport/imageWriter/fvpImageBufferWriterFactory.cpp
  lib/flowViewport/imageWriter/fvpRenderBufferWriter.cpp
  lib/flowViewport/imageWriter/fvpRenderBufferWriter.h
  lib/flowViewport/imageWriter/fvpTextureBufferWriter.cpp
  lib/flowViewport/imageWriter/fvpTextureBufferWriter.h
  lib/mayaHydra/mayaPlugin/pluginUtils.cpp
  lib/mayaHydra/mayaPlugin/renderOverride.cpp
  lib/mayaHydra/mayaPlugin/renderOverride.h
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/cpp/WriteFileTest/stormOutput.png
  test/lib/mayaUsd/render/mayaToHydra/cpp/testWriteFile.cpp
  test/lib/mayaUsd/render/mayaToHydra/cpp/testWriteFile.py
Labels: ready-for-merge

#256 Added Maya file reference test.
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/MayaReferenceTest/editMayaReference.png
  test/lib/mayaUsd/render/mayaToHydra/MayaReferenceTest/loadMayaReference.png
  test/lib/mayaUsd/render/mayaToHydra/MayaReferenceTest/unloadMayaReference.png
  test/lib/mayaUsd/render/mayaToHydra/testMayaReference.py
  test/testSamples/testMayaReference/aCube.ma
Labels: ready-for-merge, test

#258 HYDRA-1469 - Tweak coverage instructions
  doc/codeCoverageInstructions.md
Labels: ready-for-merge
