Repository Autodesk/maya-hydra, pull requests merged in 2025-03, with the labels that each got.

#259 Lanierd/hydra 1328
  cmake/modules/FindMaya.cmake
  doc/build.md
  doc/rebuildingWithCustomOpenUSDAndPreviousMayaVersion.md
  lib/mayaHydra/flowViewportAPIExamples/flowViewportAPILocator/mhFlowViewportAPILocator.cpp
Labels: documentation, ready-for-merge

#257 Added USD inherits / specializes test.
  test/lib/mayaUsd/render/mayaToHydra/CMakeLists.txt
  test/lib/mayaUsd/render/mayaToHydra/UsdInheritsSpecializesTest/inherits.png
  test/lib/mayaUsd/render/mayaToHydra/testUsdInheritsSpecializes.py
  test/testSamples/testUsdInheritsSpecializes/cubeInherits.usda
  test/testSamples/testUsdInheritsSpecializes/cubeSpecializes.usda
Labels: ready-for-merge, test

#246 Bjorn siegert adsk patch 1
  README.md
Labels: ready-for-merge

#261 HYDRA-1519 : Re-enable an image comparison in test viewport filters
  test/lib/mayaUsd/render/mayaToHydra/testViewportFilters.py
Labels: ready-for-merge
